# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: dynatracedemo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: get variables
         id: get_variables
         run: |
              export DT_DEV_DB_ID=$(curl -X GET ${{ secrets.DT_API_URL }}/config/v1/dashboards -H 'Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}' | jq -r '.[] | map(select(.name == "KQG;project=slo-evaluation;stage=dev;service=tnt-acer-svc"))| .[0].id')
              export DT_STAGING_DB_ID=$(curl -X GET ${{ secrets.DT_API_URL }}/config/v1/dashboards -H 'Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}' | jq -r '.[] | map(select(.name == "KQG;project=slo-evaluation;stage=staging;service=tnt-acer-svc"))| .[0].id')
              export DT_PROD_DB_ID=$(curl -X GET ${{ secrets.DT_API_URL }}/config/v1/dashboards -H 'Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}' | jq -r '.[] | map(select(.name == "KQG;project=slo-evaluation;stage=prod;service=tnt-acer-svc"))| .[0].id')
              export DT_PRE_DB_ID=$(curl -X GET ${{ secrets.DT_API_URL }}/config/v1/dashboards -H 'Authorization: Api-Token ${{ secrets.DT_API_TOKEN }}' | jq -r '.[] | map(select(.name == "KQG;project=deployment-gates;stage=production;service=tnt-acer-svc"))| .[0].id')
              echo $DT_DEV_DB_ID
              echo $DT_STAGING_DB_ID
              echo $DT_PROD_DB_ID
              echo $DT_PRE_DB_ID
              echo "::set-output name=DT_DEV_DB_ID::$DT_DEV_DB_ID"
              echo "::set-output name= DT_STAGING_DB_ID::$DT_STAGING_DB_ID"
              echo "::set-output name=DT_PROD_DB_ID::$DT_PROD_DB_ID"
              echo "::set-output name=DT_PRE_DB_ID::$DT_PRE_DB_ID"
