# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: dynatracedemo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: get variables
         id: get_variables
         run: |
            test=${{ secrets.DT_URL }}
            echo test >/home/ec2-user/dt_url
       - name: get variables
         run: |
            export test=$(cat /home/ec2-user/dt_url)
            echo $test
